server.port=8081
spring.application.name=sbqs-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/db_sbqs
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

# Keycloak
keycloak.server-url=http://localhost:8080
keycloak.realm=SBQS
keycloak.client-id=sbqs-frontend
keycloak.client-secret=
keycloak.admin-client-id=admin-cli
keycloak.admin-username=admin
keycloak.admin-password=admin
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/SBQS
